unique_ids:
  assets:
    standard-page.html: VHAOKY2R7RASXMZMYICVLI36VFG27UAM
    theme.css: TYKD4LAKRXOOPTNKL2VXOVRSWO7LS3MM
  forms:
    Form1: J76IBVTWMZYB4O5MZEARUQBD3BUMHZYR
  modules: {}
  scripts: {}
  server_modules: {}
